"""
SimplyStocked - Offline CSV Demo
----------------------------------
Runs the full demand_forecast pipeline using the sample CSVs generated by
generate_sample_data.py — no MySQL connection required.

Usage:
  python demand_forecast_csv_demo.py              # incremental update
  python demand_forecast_csv_demo.py --retrain    # force full retrain

Steps:
  1. Run `python generate_sample_data.py` first (creates the CSVs).
  2. Then run this script.
"""

import os
import sys
import warnings

import pandas as pd
import numpy as np

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Import shared logic directly from demand_forecast.py
# ---------------------------------------------------------------------------
# demand_forecast.py lives in the same directory; import its pure functions.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from demand_forecast import (
    build_features,
    train_full,
    update_incremental,
    load_saved_models,
    generate_restock_recommendations,
    print_results,
    load_state,
    save_state,
    models_exist,
    MODEL_OM_PATH,
    MODEL_GS_PATH,
    RESULTS_CSV_PATH,
    ANALYTICS_DIR,
    FEATURES,
    TARGET_OPEN_MARKET,
    TARGET_GROCERY_STORE,
)

# ---------------------------------------------------------------------------
# CSV paths
# ---------------------------------------------------------------------------
HERE             = os.path.dirname(os.path.abspath(__file__))
STOCK_CSV_PATH   = os.path.join(HERE, "sample_stock_snapshot.csv")
INVOICE_CSV_PATH = os.path.join(HERE, "sample_invoices.csv")


def load_csv_data(since_date: str = None):
    """
    Load stock snapshot and invoice CSVs.
    Mirrors demand_forecast.load_data() but reads from CSV instead of MySQL.
    """
    if not os.path.exists(STOCK_CSV_PATH):
        raise FileNotFoundError(
            f"Stock CSV not found: {STOCK_CSV_PATH}\n"
            "Run `python generate_sample_data.py` first."
        )
    if not os.path.exists(INVOICE_CSV_PATH):
        raise FileNotFoundError(
            f"Invoice CSV not found: {INVOICE_CSV_PATH}\n"
            "Run `python generate_sample_data.py` first."
        )

    df_stock   = pd.read_csv(STOCK_CSV_PATH)
    df_invoice = pd.read_csv(INVOICE_CSV_PATH, parse_dates=["invoice_date"])

    if since_date:
        df_invoice = df_invoice[df_invoice["invoice_date"] > since_date]

    return df_stock, df_invoice


# ---------------------------------------------------------------------------
# Main — mirrors demand_forecast.main() but uses CSVs
# ---------------------------------------------------------------------------

def main():
    force_retrain = "--retrain" in sys.argv

    state         = load_state()
    last_date     = state["last_invoice_date"]
    total_trained = state["total_invoices_trained"]

    if force_retrain or not models_exist():
        mode       = "full"
        since_date = None
        if force_retrain:
            print("\n🔄  --retrain flag detected. Performing full retrain from scratch.")
        else:
            print("\n🆕  No saved models found. Performing initial full training.")
    else:
        mode       = "incremental"
        since_date = last_date
        print(f"\n⚡  Saved models found (last trained: {state.get('trained_at', 'unknown')}).")
        print(f"    Loading incrementally — only invoices after {since_date or 'beginning'}.")

    print("Loading CSV data...")
    df_stock, df_invoice_new = load_csv_data(
        since_date=since_date if mode == "incremental" else None
    )

    # For recommendations we always want the full invoice history
    if mode == "incremental":
        _, df_invoice_all = load_csv_data(since_date=None)
    else:
        df_invoice_all = df_invoice_new

    if df_invoice_new.empty and mode == "incremental":
        print("\n✅  No new invoices since last run. Models are already up to date.")
        print("    Loading saved models to generate fresh recommendations...\n")
        model_om, model_gs = load_saved_models()
        df_features_all    = build_features(df_stock, df_invoice_all)
        results            = generate_restock_recommendations(
            df_stock, model_om, model_gs, df_features_all
        )
        print_results(results)
        results.to_csv(RESULTS_CSV_PATH, index=False)
        print(f"  Results saved to: {RESULTS_CSV_PATH}\n")
        return

    if df_invoice_new.empty and mode == "full":
        print("\n⚠️  No invoice data found in CSV. Run generate_sample_data.py first.\n")
        return

    new_count = len(df_invoice_new)
    print(f"  {new_count:,} invoice row(s) loaded.\n")

    # Preview demand variation (optional sanity check)
    df_invoice_all["invoice_date"] = pd.to_datetime(df_invoice_all["invoice_date"])
    monthly = (
        df_invoice_all
        .assign(month=lambda d: d["invoice_date"].dt.to_period("M"))
        .groupby("month")["qty_received"]
        .sum()
    )
    print("  Monthly qty_received (sample — last 6 months):")
    print(monthly.tail(6).to_string())
    print()

    # Feature engineering
    df_features_new = build_features(df_stock, df_invoice_new)
    X_new    = df_features_new[FEATURES]
    y_om_new = df_features_new[TARGET_OPEN_MARKET]
    y_gs_new = df_features_new[TARGET_GROCERY_STORE]

    df_features_all = build_features(df_stock, df_invoice_all)

    print("Training / updating models...")
    if mode == "full":
        model_om = train_full(X_new, y_om_new, "Open Market",   MODEL_OM_PATH)
        model_gs = train_full(X_new, y_gs_new, "Grocery Store", MODEL_GS_PATH)
    else:
        model_om = update_incremental(X_new, y_om_new, "Open Market",   MODEL_OM_PATH)
        model_gs = update_incremental(X_new, y_gs_new, "Grocery Store", MODEL_GS_PATH)

    latest_invoice_date = str(df_invoice_new["invoice_date"].max().date())
    save_state(latest_invoice_date, total_trained + new_count)

    print("\nGenerating restock recommendations...")
    results = generate_restock_recommendations(df_stock, model_om, model_gs, df_features_all)
    print_results(results)

    results.to_csv(RESULTS_CSV_PATH, index=False)
    print(f"  Results saved to: {RESULTS_CSV_PATH}\n")
    print(f"  Models saved to:  {ANALYTICS_DIR}\n")


if __name__ == "__main__":
    main()
